### ISSUE TITLE
Is there a way to display all the passes, incomplete and inapplicable?

### ISSUE THREAD

**Issue by thisaja** [microsoft/html-reporter-for-axe-core-dotnet#29]
In the image below, when I click the links to passes, incomplete and inapplicable nothing shows up. Is there are way to display everything?
![image](https://user-images.githubusercontent.com/42302646/221877790-d617a614-3466-4ed1-bab1-0c9c65e49ee3.png)
Below that is looks like it only shows the violations.
![image](https://user-images.githubusercontent.com/42302646/221878612-17655238-643b-4e05-afae-46d356f370bb.png)

**Comment by IsaacWalker** [comment]
Hi, yeah it's possible by using the `ReportRuleTypes` flagset enum:

```csharp
AxeHTMLReportOptions options = new()
    {
        ReportRuleTypes = ReportRuleTypes.All
    };

    AxeHTMLReport report = reporter.CreateReport(axeResults, options);
```

...by default its just violations included.

I've created an issue to not show those links for RuleTypes which are not included here #31 .
